package Utility;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.io.StringWriter;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.Date;
import java.util.Properties;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;

import org.apache.commons.io.IOUtils;



public class Email{

	//static String to = "abhishek.gautam1@girnarsoft.co.in";
	public static String[] to ={"abhishek.gautam1@girnarsoft.co.in"/*,"rohit.gaurav@girnarsoft.co.in",
	"aditya.arya@girnarsoft.co.in"*/,"prince.raj@girnarsoft.co.in","sanjeev.thakur@girnarsoft.co.in"
	/*,"bhavnish.kapoor@girnarsoft.co.in"*/};
	static String from = "abhishektest09@gmail.com";


	@SuppressWarnings("deprecation")
	public static void sendEmail(String outputDirectory,String TimeStamp,String reportdir) {


		System.out.println("directory:"+outputDirectory);
		// Create object of Property file
		Properties props = new Properties();

		// this will set host of server- you can change based on your requirement 
		props.put("mail.smtp.host", "smtp.gmail.com");

		// set the port of socket factory 
		props.put("mail.smtp.socketFactory.port", "465");

		// set socket factory
		props.put("mail.smtp.socketFactory.class","javax.net.ssl.SSLSocketFactory");

		// set the authentication to true
		props.put("mail.smtp.auth", "true");
		props.put("mail.smtp.starttls.enable", "true");
		props.put("java.net.preferIPv4Stack", "true");

		// set the port of SMTP server
		props.put("mail.smtp.port", "465");

		// This will handle the complete authentication
		Session session = Session.getInstance(props,

				new javax.mail.Authenticator() {

			protected PasswordAuthentication getPasswordAuthentication() {

				return new PasswordAuthentication("abhishektest09@gmail.com", "testing09");

			}

		});

		try {

			// Create object of MimeMessage class
			Message message = new MimeMessage(session);

			// Set the from address
			//	message.setFrom(new InternetAddress(from));

			//X-Priority values are generally numbers like 1 (for highest priority), 3 (normal) and 5 (lowest).

			message.addHeader("X-Priority", "1");
			message.setFrom(new InternetAddress(from));
			InternetAddress[] addressTo = new InternetAddress[to.length];
			for (int i = 0; i < to.length; i++)
				addressTo[i] = new InternetAddress(to[i]);
			message.setRecipients(Message.RecipientType .TO, addressTo);
			//	message.setSubject(subject);

			// Set the recipient address
			//	message.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));




			// Add the subject link
			message.setSubject("Automation_Execution_Status:Oto");

			// Create object to add multimedia type content
			BodyPart messageBodyPart1 = new MimeBodyPart();

			// Set the body of email
			/*messageBodyPart1.setText("\r\n" + " Automation suite has been executed successfully !"+"\n"+"\n"+
					"DOWNLOAD THE ATTACHMENT and then open it for detailed execution report. "
					+"\n"+"\n"+ "!!!!!! DO NOT CLICK on the attachment directly for preview !!!!!!!"
					+ "\n"+"\n"+"\n"+"\n"+"********This is a autogenerated mail by automation suite execution********");
*/
			StringWriter writer = new StringWriter();


			IOUtils.copy(new FileInputStream(new File(outputDirectory+"/emailable-report.html")), writer);


			messageBodyPart1.setContent(writer.toString(), "text/html");

			/*
			BodyPart messageBodyPart3 = new MimeBodyPart();

			messageBodyPart3.setContent("Kindly Download The Attachment To Get The Detailed Report", "text/html");
			 */
			// Create another object to add another content
			MimeBodyPart messageBodyPart2 = new MimeBodyPart();


			// Mention the file which you want to send
			String filename = System.getProperty("user.dir")+"/Reports/"+TimeStamp+"Oto_AutomationReport.html";
			System.out.println("file name:"+filename);
			// Create data source and pass the filename
			DataSource source = new FileDataSource(filename);

			// set the handler
			messageBodyPart2.setDataHandler(new DataHandler(source));
			//messageBodyPart2.setContent("Kindly Download The Attachment To Get The Detailed Report","text/html");

			// set the file
			messageBodyPart2.setFileName("OtoAutomationReport: " +TimeStamp+".html");

			// Create object of MimeMultipart class
			Multipart multipart = new MimeMultipart();

			// add body part 1
			multipart.addBodyPart(messageBodyPart2);

			// add body part 2
			multipart.addBodyPart(messageBodyPart1);

			// add body part 2
			//multipart.addBodyPart(messageBodyPart3);


			// set the content
			message.setContent(multipart,"text/html");

			Thread.sleep(6000);

			// finally send the email
			Transport.send(message);
			Thread.sleep(6000);



			System.out.println("=====Email Sent=====");

		} catch (Exception e) {
			System.out.println("Mail not sent");
			throw new RuntimeException(e);


		}



	}

}

/*

1. Login to Gmail. 
2. Access the URL as https://www.google.com/settings/security/lesssecureapps 
3. Select "Turn on"
 */